spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/tasks-manager-db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000