spring.datasource.url=jdbc:postgresql://localhost:5432/tasks-manager-db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=very-long-secret-key-at-least-256-bits-long-for-hs256
jwt.expiration=86400000